#!C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\python.exe
# EASY-INSTALL-SCRIPT: 'idlex==1.18','idlex3'
__requires__ = 'idlex==1.18'
__import__('pkg_resources').run_script('idlex==1.18', 'idlex3')
